<?php

namespace ContainerWJWEYPn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_86tzsFService extends App_KernelProdDebugContainer
{
    /**
     * Gets the private '.service_locator.86tzs_F' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.86tzs_F'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'visiteur' => ['privates', 'App\\Entity\\Visiteur', 'getVisiteurService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'visiteur' => 'App\\Entity\\Visiteur',
            'entityManager' => '?',
        ]);
    }
}
