<?php

namespace ContainerWJWEYPn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminControllerdashboardService extends App_KernelProdDebugContainer
{
    /**
     * Gets the private '.service_locator.YrrYoFx.App\Controller\AdminController::dashboard()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YrrYoFx.App\\Controller\\AdminController::dashboard()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'visiteRepo' => ['privates', 'App\\Repository\\VisiteRepository', 'getVisiteRepositoryService', true],
            'guideRepo' => ['privates', 'App\\Repository\\GuideTouristiqueRepository', 'getGuideTouristiqueRepositoryService', true],
            'visiteurRepo' => ['privates', 'App\\Repository\\VisiteurRepository', 'getVisiteurRepositoryService', true],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'visiteRepo' => 'App\\Repository\\VisiteRepository',
            'guideRepo' => 'App\\Repository\\GuideTouristiqueRepository',
            'visiteurRepo' => 'App\\Repository\\VisiteurRepository',
            'userRepo' => 'App\\Repository\\UserRepository',
        ]))->withContext('App\\Controller\\AdminController::dashboard()', $container);
    }
}
