<?php

namespace ContainerWJWEYPn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGuideTouristiqueService extends App_KernelProdDebugContainer
{
    /**
     * Gets the private 'App\Entity\GuideTouristique' shared autowired service.
     *
     * @return \App\Entity\GuideTouristique
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Entity/GuideTouristique.php';

        return $container->privates['App\\Entity\\GuideTouristique'] = new \App\Entity\GuideTouristique();
    }
}
