<?php

namespace ContainerWJWEYPn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGuideTouristiqueControllerdeleteService extends App_KernelProdDebugContainer
{
    /**
     * Gets the private '.service_locator.WJgkAFr.App\Controller\GuideTouristiqueController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.WJgkAFr'] ?? $container->load('get_ServiceLocator_WJgkAFrService'));

        if (isset($container->privates['.service_locator.WJgkAFr.App\\Controller\\GuideTouristiqueController::delete()'])) {
            return $container->privates['.service_locator.WJgkAFr.App\\Controller\\GuideTouristiqueController::delete()'];
        }

        return $container->privates['.service_locator.WJgkAFr.App\\Controller\\GuideTouristiqueController::delete()'] = $a->withContext('App\\Controller\\GuideTouristiqueController::delete()', $container);
    }
}
