<?php

namespace ContainerWJWEYPn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGuideTouristiqueFormService extends App_KernelProdDebugContainer
{
    /**
     * Gets the private 'App\Form\GuideTouristiqueForm' shared autowired service.
     *
     * @return \App\Form\GuideTouristiqueForm
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/GuideTouristiqueForm.php';

        return $container->privates['App\\Form\\GuideTouristiqueForm'] = new \App\Form\GuideTouristiqueForm();
    }
}
