<?php

namespace ContainerWJWEYPn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGuideTouristiqueControllershowService extends App_KernelProdDebugContainer
{
    /**
     * Gets the private '.service_locator.okXDppS.App\Controller\GuideTouristiqueController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.okXDppS.App\\Controller\\GuideTouristiqueController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'guideTouristique' => ['privates', 'App\\Entity\\GuideTouristique', 'getGuideTouristiqueService', true],
        ], [
            'guideTouristique' => 'App\\Entity\\GuideTouristique',
        ]))->withContext('App\\Controller\\GuideTouristiqueController::show()', $container);
    }
}
