<?php

namespace ContainerWJWEYPn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaxVisiteursValidatorService extends App_KernelProdDebugContainer
{
    /**
     * Gets the private 'App\Validator\MaxVisiteursValidator' shared autowired service.
     *
     * @return \App\Validator\MaxVisiteursValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/src/Validator/MaxVisiteursValidator.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Validator\\MaxVisiteursValidator'])) {
            return $container->privates['App\\Validator\\MaxVisiteursValidator'];
        }

        return $container->privates['App\\Validator\\MaxVisiteursValidator'] = new \App\Validator\MaxVisiteursValidator($a);
    }
}
