<?php

namespace ContainerWJWEYPn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatsControllerindexService extends App_KernelProdDebugContainer
{
    /**
     * Gets the private '.service_locator.q0AKet5.App\Controller\StatsController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.q0AKet5.App\\Controller\\StatsController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'visiteRepo' => ['privates', 'App\\Repository\\VisiteRepository', 'getVisiteRepositoryService', true],
            'visiteurRepo' => ['privates', 'App\\Repository\\VisiteurRepository', 'getVisiteurRepositoryService', true],
        ], [
            'visiteRepo' => 'App\\Repository\\VisiteRepository',
            'visiteurRepo' => 'App\\Repository\\VisiteurRepository',
        ]))->withContext('App\\Controller\\StatsController::index()', $container);
    }
}
