<?php

namespace ContainerWJWEYPn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVisiteControllerindexService extends App_KernelProdDebugContainer
{
    /**
     * Gets the private '.service_locator.tHLA38G.App\Controller\VisiteController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tHLA38G.App\\Controller\\VisiteController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'visiteRepository' => ['privates', 'App\\Repository\\VisiteRepository', 'getVisiteRepositoryService', true],
        ], [
            'visiteRepository' => 'App\\Repository\\VisiteRepository',
        ]))->withContext('App\\Controller\\VisiteController::index()', $container);
    }
}
