<?php

namespace ContainerWJWEYPn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVisiteControllerdeleteService extends App_KernelProdDebugContainer
{
    /**
     * Gets the private '.service_locator.m1MnzzT.App\Controller\VisiteController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.m1MnzzT'] ?? $container->load('get_ServiceLocator_M1MnzzTService'));

        if (isset($container->privates['.service_locator.m1MnzzT.App\\Controller\\VisiteController::delete()'])) {
            return $container->privates['.service_locator.m1MnzzT.App\\Controller\\VisiteController::delete()'];
        }

        return $container->privates['.service_locator.m1MnzzT.App\\Controller\\VisiteController::delete()'] = $a->withContext('App\\Controller\\VisiteController::delete()', $container);
    }
}
