<?php

namespace ContainerWJWEYPn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVisiteControllershowService extends App_KernelProdDebugContainer
{
    /**
     * Gets the private '.service_locator.2rjS4KL.App\Controller\VisiteController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2rjS4KL.App\\Controller\\VisiteController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'visite' => ['privates', 'App\\Entity\\Visite', 'getVisiteService', true],
        ], [
            'visite' => 'App\\Entity\\Visite',
        ]))->withContext('App\\Controller\\VisiteController::show()', $container);
    }
}
