<?php

namespace ContainerWJWEYPn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVisiteurControllershowService extends App_KernelProdDebugContainer
{
    /**
     * Gets the private '.service_locator.WNiQDQo.App\Controller\VisiteurController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WNiQDQo.App\\Controller\\VisiteurController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'visiteur' => ['privates', 'App\\Entity\\Visiteur', 'getVisiteurService', true],
        ], [
            'visiteur' => 'App\\Entity\\Visiteur',
        ]))->withContext('App\\Controller\\VisiteurController::show()', $container);
    }
}
