<?php

namespace ContainerWJWEYPn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVisiteService extends App_KernelProdDebugContainer
{
    /**
     * Gets the private 'App\Entity\Visite' shared autowired service.
     *
     * @return \App\Entity\Visite
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Entity/Visite.php';

        return $container->privates['App\\Entity\\Visite'] = new \App\Entity\Visite();
    }
}
