<?php

namespace ContainerEW3p1sO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OkXDppSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.okXDppS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.okXDppS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'guideTouristique' => ['privates', '.errored..service_locator.okXDppS.App\\Entity\\GuideTouristique', NULL, 'Cannot autowire service ".service_locator.okXDppS": it needs an instance of "App\\Entity\\GuideTouristique" but this type has been excluded in "config/services.yaml".'],
        ], [
            'guideTouristique' => 'App\\Entity\\GuideTouristique',
        ]);
    }
}
