<?php

namespace ContainerEW3p1sO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PfB6VCUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PfB6VCU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PfB6VCU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\GuideTouristiqueController::show' => ['privates', '.service_locator.okXDppS.App\\Controller\\GuideTouristiqueController::show()', 'getGuideTouristiqueControllershowService', true],
            'App\\Controller\\GuideTouristiqueController::edit' => ['privates', '.service_locator.okXDppS.App\\Controller\\GuideTouristiqueController::edit()', 'getGuideTouristiqueControllereditService', true],
            'App\\Controller\\GuideTouristiqueController::delete' => ['privates', '.service_locator.okXDppS.App\\Controller\\GuideTouristiqueController::delete()', 'getGuideTouristiqueControllerdeleteService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.OzEre6h.App\\Controller\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\UserController::new' => ['privates', '.service_locator.A84gqGd.App\\Controller\\UserController::new()', 'getUserControllernewService', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.EWAQaZu.App\\Controller\\UserController::show()', 'getUserControllershowService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.zzHOEcp.App\\Controller\\UserController::edit()', 'getUserControllereditService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.WkfvUVe.App\\Controller\\UserController::delete()', 'getUserControllerdeleteService', true],
            'App\\Controller\\VisiteController::show' => ['privates', '.service_locator.2rjS4KL.App\\Controller\\VisiteController::show()', 'getVisiteControllershowService', true],
            'App\\Controller\\VisiteController::edit' => ['privates', '.service_locator.2rjS4KL.App\\Controller\\VisiteController::edit()', 'getVisiteControllereditService', true],
            'App\\Controller\\VisiteController::delete' => ['privates', '.service_locator.2rjS4KL.App\\Controller\\VisiteController::delete()', 'getVisiteControllerdeleteService', true],
            'App\\Controller\\VisiteurController::index' => ['privates', '.service_locator._deZ7.n.App\\Controller\\VisiteurController::index()', 'getVisiteurControllerindexService', true],
            'App\\Controller\\VisiteurController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\VisiteurController::new()', 'getVisiteurControllernewService', true],
            'App\\Controller\\VisiteurController::show' => ['privates', '.service_locator.WNiQDQo.App\\Controller\\VisiteurController::show()', 'getVisiteurControllershowService', true],
            'App\\Controller\\VisiteurController::edit' => ['privates', '.service_locator.86tzs_F.App\\Controller\\VisiteurController::edit()', 'getVisiteurControllereditService', true],
            'App\\Controller\\VisiteurController::delete' => ['privates', '.service_locator.86tzs_F.App\\Controller\\VisiteurController::delete()', 'getVisiteurControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\GuideTouristiqueController:show' => ['privates', '.service_locator.okXDppS.App\\Controller\\GuideTouristiqueController::show()', 'getGuideTouristiqueControllershowService', true],
            'App\\Controller\\GuideTouristiqueController:edit' => ['privates', '.service_locator.okXDppS.App\\Controller\\GuideTouristiqueController::edit()', 'getGuideTouristiqueControllereditService', true],
            'App\\Controller\\GuideTouristiqueController:delete' => ['privates', '.service_locator.okXDppS.App\\Controller\\GuideTouristiqueController::delete()', 'getGuideTouristiqueControllerdeleteService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.OzEre6h.App\\Controller\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\UserController:new' => ['privates', '.service_locator.A84gqGd.App\\Controller\\UserController::new()', 'getUserControllernewService', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.EWAQaZu.App\\Controller\\UserController::show()', 'getUserControllershowService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.zzHOEcp.App\\Controller\\UserController::edit()', 'getUserControllereditService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.WkfvUVe.App\\Controller\\UserController::delete()', 'getUserControllerdeleteService', true],
            'App\\Controller\\VisiteController:show' => ['privates', '.service_locator.2rjS4KL.App\\Controller\\VisiteController::show()', 'getVisiteControllershowService', true],
            'App\\Controller\\VisiteController:edit' => ['privates', '.service_locator.2rjS4KL.App\\Controller\\VisiteController::edit()', 'getVisiteControllereditService', true],
            'App\\Controller\\VisiteController:delete' => ['privates', '.service_locator.2rjS4KL.App\\Controller\\VisiteController::delete()', 'getVisiteControllerdeleteService', true],
            'App\\Controller\\VisiteurController:index' => ['privates', '.service_locator._deZ7.n.App\\Controller\\VisiteurController::index()', 'getVisiteurControllerindexService', true],
            'App\\Controller\\VisiteurController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\VisiteurController::new()', 'getVisiteurControllernewService', true],
            'App\\Controller\\VisiteurController:show' => ['privates', '.service_locator.WNiQDQo.App\\Controller\\VisiteurController::show()', 'getVisiteurControllershowService', true],
            'App\\Controller\\VisiteurController:edit' => ['privates', '.service_locator.86tzs_F.App\\Controller\\VisiteurController::edit()', 'getVisiteurControllereditService', true],
            'App\\Controller\\VisiteurController:delete' => ['privates', '.service_locator.86tzs_F.App\\Controller\\VisiteurController::delete()', 'getVisiteurControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\GuideTouristiqueController::show' => '?',
            'App\\Controller\\GuideTouristiqueController::edit' => '?',
            'App\\Controller\\GuideTouristiqueController::delete' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::new' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\VisiteController::show' => '?',
            'App\\Controller\\VisiteController::edit' => '?',
            'App\\Controller\\VisiteController::delete' => '?',
            'App\\Controller\\VisiteurController::index' => '?',
            'App\\Controller\\VisiteurController::new' => '?',
            'App\\Controller\\VisiteurController::show' => '?',
            'App\\Controller\\VisiteurController::edit' => '?',
            'App\\Controller\\VisiteurController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\GuideTouristiqueController:show' => '?',
            'App\\Controller\\GuideTouristiqueController:edit' => '?',
            'App\\Controller\\GuideTouristiqueController:delete' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:new' => '?',
            'App\\Controller\\UserController:show' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\VisiteController:show' => '?',
            'App\\Controller\\VisiteController:edit' => '?',
            'App\\Controller\\VisiteController:delete' => '?',
            'App\\Controller\\VisiteurController:index' => '?',
            'App\\Controller\\VisiteurController:new' => '?',
            'App\\Controller\\VisiteurController:show' => '?',
            'App\\Controller\\VisiteurController:edit' => '?',
            'App\\Controller\\VisiteurController:delete' => '?',
        ]);
    }
}
