<?php

namespace ContainerEW3p1sO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2rjS4KLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2rjS4KL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2rjS4KL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'visite' => ['privates', '.errored..service_locator.2rjS4KL.App\\Entity\\Visite', NULL, 'Cannot autowire service ".service_locator.2rjS4KL": it needs an instance of "App\\Entity\\Visite" but this type has been excluded in "config/services.yaml".'],
        ], [
            'visite' => 'App\\Entity\\Visite',
        ]);
    }
}
