<?php

namespace ContainerEW3p1sO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_86tzsFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.86tzs_F' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.86tzs_F'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'visiteur' => ['privates', '.errored..service_locator.86tzs_F.App\\Entity\\Visiteur', NULL, 'Cannot autowire service ".service_locator.86tzs_F": it needs an instance of "App\\Entity\\Visiteur" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'visiteur' => 'App\\Entity\\Visiteur',
            'entityManager' => '?',
        ]);
    }
}
