<?php

namespace ContainerEW3p1sO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGuideTouristiqueControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.okXDppS.App\Controller\GuideTouristiqueController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.okXDppS.App\\Controller\\GuideTouristiqueController::show()'] = ($container->privates['.service_locator.okXDppS'] ?? $container->load('get_ServiceLocator_OkXDppSService'))->withContext('App\\Controller\\GuideTouristiqueController::show()', $container);
    }
}
