<?php

namespace ContainerEW3p1sO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHashPasswordCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\HashPasswordCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\HashPasswordCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:hash-password', [], 'Hashes a password using Symfony\'s password encoder.', false, #[\Closure(name: 'App\\Command\\HashPasswordCommand')] fn (): \App\Command\HashPasswordCommand => ($container->privates['App\\Command\\HashPasswordCommand'] ?? $container->load('getHashPasswordCommandService')));
    }
}
