<?php

namespace ContainerEW3p1sO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVisiteControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2rjS4KL.App\Controller\VisiteController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2rjS4KL.App\\Controller\\VisiteController::delete()'] = ($container->privates['.service_locator.2rjS4KL'] ?? $container->load('get_ServiceLocator_2rjS4KLService'))->withContext('App\\Controller\\VisiteController::delete()', $container);
    }
}
