<?php

namespace ContainerEW3p1sO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVisiteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.2rjS4KL.App\Entity\Visite' shared service.
     *
     * @return \App\Entity\Visite
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.2rjS4KL": it needs an instance of "App\\Entity\\Visite" but this type has been excluded in "config/services.yaml".');
    }
}
