<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEW3p1sO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEW3p1sO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEW3p1sO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEW3p1sO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEW3p1sO\App_KernelDevDebugContainer([
    'container.build_hash' => 'EW3p1sO',
    'container.build_id' => '91baa288',
    'container.build_time' => 1750630470,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEW3p1sO');
