<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTJNAY3c\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTJNAY3c/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTJNAY3c.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTJNAY3c\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTJNAY3c\App_KernelDevDebugContainer([
    'container.build_hash' => 'TJNAY3c',
    'container.build_id' => '880b415c',
    'container.build_time' => 1750990759,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTJNAY3c');
