<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSC8dggE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSC8dggE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSC8dggE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSC8dggE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSC8dggE\App_KernelDevDebugContainer([
    'container.build_hash' => 'SC8dggE',
    'container.build_id' => '76ffdcd4',
    'container.build_time' => 1750946771,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSC8dggE');
