<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.beebd2e7.js',
                '/build/232.320a6064.js',
                '/build/app.b0a62ab5.js',
            ],
            'css' => [
                '/build/app.bbf3335e.css',
            ],
        ],
    ],
],

]];
