<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWJWEYPn\App_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWJWEYPn/App_KernelProdDebugContainer.php') {
    touch(__DIR__.'/ContainerWJWEYPn.legacy');

    return;
}

if (!\class_exists(App_KernelProdDebugContainer::class, false)) {
    \class_alias(\ContainerWJWEYPn\App_KernelProdDebugContainer::class, App_KernelProdDebugContainer::class, false);
}

return new \ContainerWJWEYPn\App_KernelProdDebugContainer([
    'container.build_hash' => 'WJWEYPn',
    'container.build_id' => '49683041',
    'container.build_time' => 1750225396,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWJWEYPn');
