<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.beebd2e7.js',
                '/build/490.60fee697.js',
                '/build/app.9371a76e.js',
            ],
            'css' => [
                '/build/app.9d5d4d77.css',
            ],
        ],
    ],
],

]];
