<?php

namespace ContainerEW3p1sO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGuideTouristiqueControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\GuideTouristiqueController' shared autowired service.
     *
     * @return \App\Controller\GuideTouristiqueController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/GuideTouristiqueController.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/filesystem/Filesystem.php';

        $container->services['App\\Controller\\GuideTouristiqueController'] = $instance = new \App\Controller\GuideTouristiqueController(($container->privates['App\\Repository\\GuideTouristiqueRepository'] ?? $container->load('getGuideTouristiqueRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['knp_paginator'] ?? $container->load('getKnpPaginatorService')), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')), ($container->privates['App\\Service\\FileUploader'] ?? $container->load('getFileUploaderService')), ($container->privates['filesystem'] ??= new \Symfony\Component\Filesystem\Filesystem()));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\GuideTouristiqueController', $container));

        return $instance;
    }
}
