<?php

namespace ContainerEW3p1sO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGuideTouristiqueService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.okXDppS.App\Entity\GuideTouristique' shared service.
     *
     * @return \App\Entity\GuideTouristique
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.okXDppS": it needs an instance of "App\\Entity\\GuideTouristique" but this type has been excluded in "config/services.yaml".');
    }
}
