<?php

namespace ContainerEW3p1sO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHashPasswordCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\HashPasswordCommand' shared autowired service.
     *
     * @return \App\Command\HashPasswordCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/HashPasswordCommand.php';

        $container->privates['App\\Command\\HashPasswordCommand'] = $instance = new \App\Command\HashPasswordCommand(($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')));

        $instance->setName('app:hash-password');
        $instance->setDescription('Hashes a password using Symfony\'s password encoder.');

        return $instance;
    }
}
