<?php

namespace ContainerEW3p1sO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVisiteurControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.86tzs_F.App\Controller\VisiteurController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.86tzs_F'] ?? $container->load('get_ServiceLocator_86tzsFService'));

        if (isset($container->privates['.service_locator.86tzs_F.App\\Controller\\VisiteurController::delete()'])) {
            return $container->privates['.service_locator.86tzs_F.App\\Controller\\VisiteurController::delete()'];
        }

        return $container->privates['.service_locator.86tzs_F.App\\Controller\\VisiteurController::delete()'] = $a->withContext('App\\Controller\\VisiteurController::delete()', $container);
    }
}
