<?php

namespace ContainerEW3p1sO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVisiteurControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WNiQDQo.App\Controller\VisiteurController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WNiQDQo.App\\Controller\\VisiteurController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'visiteur' => ['privates', '.errored..service_locator.WNiQDQo.App\\Entity\\Visiteur', NULL, 'Cannot autowire service ".service_locator.WNiQDQo": it needs an instance of "App\\Entity\\Visiteur" but this type has been excluded in "config/services.yaml".'],
        ], [
            'visiteur' => 'App\\Entity\\Visiteur',
        ]))->withContext('App\\Controller\\VisiteurController::show()', $container);
    }
}
