<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Visite extends \App\Entity\Visite implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'commentaire' => [parent::class, 'commentaire', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'date' => [parent::class, 'date', null, 16],
        "\0".parent::class."\0".'duree' => [parent::class, 'duree', null, 16],
        "\0".parent::class."\0".'guide' => [parent::class, 'guide', null, 16],
        "\0".parent::class."\0".'heureDebut' => [parent::class, 'heureDebut', null, 16],
        "\0".parent::class."\0".'heureFin' => [parent::class, 'heureFin', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'lieu' => [parent::class, 'lieu', null, 16],
        "\0".parent::class."\0".'nombreMaxVisiteurs' => [parent::class, 'nombreMaxVisiteurs', null, 16],
        "\0".parent::class."\0".'pays' => [parent::class, 'pays', null, 16],
        "\0".parent::class."\0".'photoFilename' => [parent::class, 'photoFilename', null, 16],
        "\0".parent::class."\0".'prix' => [parent::class, 'prix', null, 16],
        "\0".parent::class."\0".'visiteurs' => [parent::class, 'visiteurs', null, 16],
        'commentaire' => [parent::class, 'commentaire', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'date' => [parent::class, 'date', null, 16],
        'duree' => [parent::class, 'duree', null, 16],
        'guide' => [parent::class, 'guide', null, 16],
        'heureDebut' => [parent::class, 'heureDebut', null, 16],
        'heureFin' => [parent::class, 'heureFin', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'lieu' => [parent::class, 'lieu', null, 16],
        'nombreMaxVisiteurs' => [parent::class, 'nombreMaxVisiteurs', null, 16],
        'pays' => [parent::class, 'pays', null, 16],
        'photoFilename' => [parent::class, 'photoFilename', null, 16],
        'prix' => [parent::class, 'prix', null, 16],
        'visiteurs' => [parent::class, 'visiteurs', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
