controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
api_login:
    path: /api/login_check  # Endpoint corrigé
    methods: POST
    controller: lexik_jwt_authentication.controller.authentication